# Form implementation generated from reading ui file '/home/laurent/Documents/Python/uv_packages/Graphisme/media_restorer/src/media_restorer/extensions/pre_classement/views/main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableResults = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableResults.setAlternatingRowColors(True)
        self.tableResults.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableResults.setObjectName("tableResults")
        self.tableResults.setColumnCount(0)
        self.tableResults.setRowCount(0)
        self.verticalLayout.addWidget(self.tableResults)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menubar.setObjectName("menubar")
        self.menuClassement = QtWidgets.QMenu(parent=self.menubar)
        self.menuClassement.setObjectName("menuClassement")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionClassify = QtGui.QAction(parent=MainWindow)
        self.actionClassify.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/media-playback-start.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClassify.setIcon(icon)
        self.actionClassify.setObjectName("actionClassify")
        self.actionWriteTags = QtGui.QAction(parent=MainWindow)
        self.actionWriteTags.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/document-save-2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionWriteTags.setIcon(icon1)
        self.actionWriteTags.setObjectName("actionWriteTags")
        self.actionExportCsv = QtGui.QAction(parent=MainWindow)
        self.actionExportCsv.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/document-save-as.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExportCsv.setIcon(icon2)
        self.actionExportCsv.setObjectName("actionExportCsv")
        self.menuClassement.addAction(self.actionClassify)
        self.menuClassement.addAction(self.actionWriteTags)
        self.menuClassement.addAction(self.actionExportCsv)
        self.menubar.addAction(self.menuClassement.menuAction())
        self.toolBar.addAction(self.actionClassify)
        self.toolBar.addAction(self.actionWriteTags)
        self.toolBar.addAction(self.actionExportCsv)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pré-classement — tri grossier du corpus"))
        self.tableResults.setSortingEnabled(True)
        self.menuClassement.setTitle(_translate("MainWindow", "Classement"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "Outils"))
        self.actionClassify.setText(_translate("MainWindow", "Classer"))
        self.actionClassify.setToolTip(_translate("MainWindow", "Mesurer toutes les images de la cible et les classer selon les critères cochés (Ctrl+R)"))
        self.actionClassify.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionWriteTags.setText(_translate("MainWindow", "Écrire les étiquettes"))
        self.actionWriteTags.setToolTip(_translate("MainWindow", "Écrire le classement dans les métadonnées de chaque image, au format DigiKam (confirmation demandée) (Ctrl+S)"))
        self.actionWriteTags.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExportCsv.setText(_translate("MainWindow", "Exporter en CSV"))
        self.actionExportCsv.setToolTip(_translate("MainWindow", "Enregistrer le tableau de classement dans un fichier CSV, sans modifier les images (Ctrl+E)"))
        self.actionExportCsv.setShortcut(_translate("MainWindow", "Ctrl+E"))
